### ISSUE TITLE
dwt not in the dub repositry

### ISSUE THREAD

**Issue by jspashett** [d-widget-toolkit/dwt#15] opened 2015-03-04 10:19 UTC
Can dwt be added to the dub repository at code.dlang.org? Just trying to give it a try out and it makes things much easier when it's in the repository.

**Comment by jacob-carlborg** [comment] 2015-03-04 19:58
Closing this as a duplicate of issue #12. Please also see https://github.com/d-widget-toolkit/dwt/pull/13.

**Closed by jacob-carlborg** 2015-03-04 19:58 UTC
